import Head from 'next/head'
import Header from '../components/Header'
import Filter from '../components/Filter'
import PacientsTable from '../components/PacientsTable'
import styles from '../styles/Home.module.css'
import LoadMore from '../components/LoadMore'

export default function Home() {
  return (
    <div className="overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Filter />
        <PacientsTable />
        <div className="d-flex row justify-content-center">
          <LoadMore />
        </div>
      </main>
    </div>
  )
}
