import Head from 'next/head'
import Header from '../components/Header'
import Filter from '../components/Filter'
import PacientsTable from '../components/PacientsTable'
import styles from '../styles/Home.module.css'
import LoadMore from '../components/LoadMore'
import { useRouter } from 'next/router'
import Modal from 'react-modal'
import User from '../components/User'

Modal.setAppElement('#__next')

export default function Home() {
  const router = useRouter()
  return (
    <div className="overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
     { /*<!--Modal
        isOpen={!!router.query.userId}
        onRequestClose={() => router.push('/')}
        contentLabel="User modal"
      >
        <div>
          <User userId={router.query.userId} />
          this is my id: {router.query.userId}
        </div>

     </Modal>*/}
        <Header />
        <Filter />
        <PacientsTable />
        <div className="d-flex row justify-content-center">
          <LoadMore />
        </div>
      </main>
    </div>
  )
}
